// Client-side port of the FastAPI endpoints in backend/main.py.
// The static demo has no server, so these run in the browser on bundled recipe data
// (generated by backend/export_json.py). Keep behaviour in sync with main.py.

// Python's round(): half-to-even
function pyRound(x, digits = 0) {
  const m = 10 ** digits;
  const v = x * m;
  const r = Math.round(v);
  const isHalf = Math.abs(v % 1) === 0.5;
  return (isHalf && r % 2 !== 0 ? r - 1 : r) / m;
}

// Codepoint ordering, same as Python string comparison
function cmp(a, b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

export function recipeDetail(recipes, recipeId, guests) {
  const r = recipes.find((x) => x.id === recipeId);
  if (!r) return null;
  const scale = guests && r.base_servings ? guests / r.base_servings : 1.0;

  const ingredients = r.ingredients.map((ri) => {
    let qtyStr;
    if (ri.quantity_type === "to_taste") {
      qtyStr = "do smaku";
    } else if (ri.quantity_type === "descriptive") {
      qtyStr = ri.display_note || "wg potrzeb";
    } else if (ri.quantity != null) {
      const raw = ri.quantity * scale;
      let q;
      if (ri.unit === "szt") q = Math.max(1, pyRound(raw));
      else if (ri.unit === "g") q = pyRound(raw / 10) * 10;
      else q = Number.isInteger(raw) ? raw : pyRound(raw, 1);
      qtyStr = ri.unit ? `${q} ${ri.unit}` : String(q);
      if (ri.display_note) qtyStr += ` (${ri.display_note})`;
    } else {
      qtyStr = ri.display_note || "";
    }
    return { name: ri.name, qty: qtyStr };
  });

  const steps = (r.instructions || "")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => line.replace(/^\d+\.\s*/, ""));

  return {
    id: r.id,
    name: r.name,
    notes: r.notes || "",
    steps,
    effort_level: r.effort_level,
    cost_per_person: r.cost_per_person,
    base_servings: r.base_servings,
    ingredients,
  };
}

const DIET_ALLOWED = {
  miesne: ["miesne"],
  wegetarianskie: ["wegetarianskie", "weganskie"],
  weganskie: ["weganskie"],
  rybne: ["rybne", "wegetarianskie", "weganskie"],
};

const DIET_PRIORITY = {
  miesne: ["miesne", "rybne", "wegetarianskie", "weganskie"],
  wegetarianskie: ["wegetarianskie", "weganskie"],
  weganskie: ["weganskie"],
  rybne: ["rybne", "wegetarianskie", "weganskie"],
};

export function suggestRecipes(recipes, input) {
  let list = recipes;

  if (input.party_type) {
    list = list.filter((r) => r.party_types.split(",").includes(input.party_type));
  }

  const allowed = DIET_ALLOWED[input.diet];
  if (allowed) {
    list = list.filter((r) => r.is_universal || r.diet_tags.split(",").some((t) => allowed.includes(t)));
  }

  // effort_level 1 → max 10 min/danie, 2 → max 20 min/danie, 3 → brak limitu
  const timeLimit = { 1: 10, 2: 20, 3: null }[input.effort_level];
  if (timeLimit != null) {
    list = list.filter((r) => r.prep_time_minutes <= timeLimit);
  }
  const perDishBudget = input.budget_per_person / 6;
  list = list.filter((r) => r.cost_per_person <= perDishBudget);

  // Deduplicate by group_name — keep the variant that best matches the requested diet.
  // For "mieszane" skip deduplication so all variants are available in the swap/add pool.
  if (input.diet !== "mieszane") {
    const priority = DIET_PRIORITY[input.diet] ?? [];
    const score = (r) => {
      const idx = r.diet_tags.split(",").map((t) => priority.indexOf(t)).filter((i) => i >= 0);
      return idx.length ? Math.min(...idx) : 999;
    };
    const seen = new Map();
    for (const r of list) {
      const key = r.group_name ? r.group_name : String(r.id);
      if (!seen.has(key) || score(r) < score(seen.get(key))) seen.set(key, r);
    }
    list = [...seen.values()];
  }

  return list.map((r) => ({
    id: r.id,
    name: r.name,
    diet_tags: r.diet_tags,
    effort_level: r.effort_level,
    prep_time_minutes: r.prep_time_minutes,
    cost_per_person: r.cost_per_person,
    scaled_cost: pyRound(r.cost_per_person * input.guests, 2),
    is_universal: r.is_universal,
  }));
}

export function shoppingList(recipes, { recipe_ids, guests, num_dishes = 6, hungry = false }) {
  const exactTotals = new Map();
  const specialItems = new Map();

  const portionFactor = num_dishes > 0 ? Math.min(1.0, 6.0 / num_dishes) : 1.0;
  const totalFactor = portionFactor * (hungry ? 1.3 : 1.0);

  for (const recipeId of recipe_ids) {
    const recipe = recipes.find((r) => r.id === recipeId);
    if (!recipe) continue;
    for (const ri of recipe.ingredients) {
      if (ri.quantity_type === "exact") {
        const scaled = ri.quantity * (guests / recipe.base_servings) * totalFactor;
        const existing = exactTotals.get(ri.ingredient_id);
        if (existing) {
          existing.total_quantity += scaled;
        } else {
          exactTotals.set(ri.ingredient_id, {
            ingredient_name: ri.name,
            category: ri.category,
            total_quantity: scaled,
            unit: ri.unit,
            display_note: null,
          });
        }
      } else if (!specialItems.has(ri.ingredient_id)) {
        specialItems.set(ri.ingredient_id, {
          ingredient_name: ri.name,
          category: ri.category,
          total_quantity: null,
          unit: null,
          display_note: ri.display_note,
        });
      }
    }
  }

  return [...exactTotals.values(), ...specialItems.values()].sort(
    (a, b) => cmp(a.category, b.category) || cmp(a.ingredient_name, b.ingredient_name)
  );
}
